Working on the glue example

diff --git a/glue-example/local-example/.scripts/__run b/glue-example/local-example/.scripts/__run
--- a/glue-example/local-example/.scripts/__run
+++ b/glue-example/local-example/.scripts/__run
@@ -1,12 +1,25 @@
-#!/bin/bash
+#!/bin/bash -e
 
 WORKSPACE_LOCATION=$(pwd)
-PROFILE_NAME="default"
+AWS_PROFILE="default"
+
+CREDENTIAL=$(aws sts --profile $AWS_PROFILE get-session-token | jq .Credentials)
+if [ -z "$CREDENTIAL" ]
+then
+    echo "Unable to get the AWS credentials"
+    exit 1
+fi
+
+AWS_ACCESS_KEY_ID=$(echo $CREDENTIAL | jq -r .AccessKeyId)
+AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIAL | jq -r .SecretAccessKey)
+AWS_SESSION_TOKEN=$(echo $CREDENTIAL | jq -r .SessionToken)
 
 docker run -it \
-    -v ~/.aws:/home/glue_user/.aws \
+    -v ~/.aws:/home/glue_user/.aws:ro \
     -v $WORKSPACE_LOCATION:/home/glue_user/workspace/ \
-    -e AWS_PROFILE=$PROFILE_NAME \
+    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
+    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
+    -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
     -e DISABLE_SSL=true \
     --rm \
     -p 4040:4040 \
